### ISSUE TITLE
Extending `CELERYBEAT_SCHEDULE`

### ISSUE THREAD

**Issue by dset0x** [inveniosoftware/invenio-celery#4]
It appears that there is currently no way to add a key to the [CELERYBEAT_SCHEDULE](https://github.com/inveniosoftware/invenio-celery/blob/master/invenio_celery/config.py#L97) variable, instead of completely overwriting it (with no knowledge of what we're overwriting).

Such functionality would enable modules to declare what they want to add to the beat, instead of the administrator of the overlay being responsible of creating this schedule on their own.

Example use-case:
The future `checker` requires being able to run tasks periodically, and adding these periodic tasks to celery beat is the closest-to-native-invenio solution we could come up with.

**Comment by lnielsen** [comment]
My experience is that in the overlay you want full control of which jobs are run, so I think the best is just make it easy for the overlay to import a partial schedule:

```python
# overlay/config.py

from invenio_checker.config import CHECKER_CELERY_SCHEDULE

CELERYBEAT_SCHEDULE = {}
CELERYBEAT_SCHEDULE.update(CHECKER_CELERY_SCHEDULE)
```

**Comment by dset0x** [comment]
That's good enough for me.

@jalavik you may be interested in this method.

**Comment by jalavik** [comment]
:+1:
