### ISSUE TITLE
global: celery v4.2.0 breaks task discovery

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-celery#53]
Because the extension is calling `celery.autodiscover_tasks` with an empty string (`''`) as the `related_name` argument, this [line eventually fails in celery](https://github.com/celery/celery/blob/9778f2bfe0bf0c4f3d554bdcb479ad769a349fc2/celery/loaders/base.py#L263) (responsible commit: https://github.com/WoaDmulL/celery/commit/c089f86e338c852043bc2ee25be2b82fd53a45a6).

Since it's not very convenient to change all of the invenio package entrypoints to support a `invenio_package` + `tasks` naming convention, there's two solutions:

1. Pin `celery` to `<4.2`
2. Wait until https://github.com/celery/celery/issues/4810 is resolved in upstream

**Comment by lnielsen** [comment]
Let's put a release out that pins Celery <4.2 until resolved.

**Comment by slint** [comment]
https://github.com/celery/celery/issues/4810 is closed via https://github.com/celery/celery/pull/4813

Now we can wait for the next release (4.2.1 or 4.3.0)

**Comment by dinosk** [comment]
This still fails with celery 4.2.1, should we pin?
