### ISSUE TITLE
global: python3.7 not compatible yet with celery 4.x

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-celery#57]
Because of some required renaming in celery (i.e. `async` is now a keyword in python3.7) running Invenio with Celery is not possible in Python 3.7. This is planned to be fixed in Celery 5.x...

Relevant celery issues: https://github.com/celery/celery/issues/4500, https://github.com/celery/celery/issues/4849

**Comment by alexsdutton** [comment]
As celery now supports Python 3.7 as of at least 4.3.0, (https://github.com/celery/celery/blob/v4.3.0/setup.py), this can probably be resolved :-).
