### ISSUE TITLE
Currently uninstallable on Python 3.7 due to dependency version mismatches

### ISSUE THREAD

**Issue by alexsdutton** [inveniosoftware/invenio-celery#64]
In invenio-celery:
```python
install_requires=[
    # Avoid version 4.3 it breaks the emails with datetime
    # https://github.com/celery/celery/pull/5606
    'celery>=4.2.1,<4.3.0',
    ''Flask-CeleryExt>=0.3.0',
]```
In Flask-CeleryExt (an invenio-managed project):
```python
install_requires=[
    'celery>=3.1;python_version<"3.7"',
    'celery>=4.3;python_version=="3.7"',
]
```
This means that dependency resolution fails when installing `invenio-celery` in Python 3.7. I know that celery 4.4 is still in RC, but can we relax one of these so that it can be installed?

**Comment by lnielsen** [comment]
v4.4. is out so we should be able to support 3.7/8. Adding to fix latest in next sprint (early march)
